In [1]:
import numpy as np

In [4]:
A = np.array([[1,2],[3,4]])
B = np.array([[2,0],[1,2]])
print(A)
print(B)

[[1 2]
 [3 4]]
[[2 0]
 [1 2]]


In [7]:
#multiplicacion de matrices
#por sintaxis
C = A @ B
#por funciones de numpy
C = np.dot(A,B)
print(C)

[[ 4  4]
 [10  8]]


In [11]:
#hay que recordar las leyes de la algebra lineal
#como el producto punto
x = np.array([2,3])
y = np.array([5,2])
x@y
#determinante de matrices
np.linalg.det(B)

np.float64(4.0)

In [13]:
#inversa de una matriz
#una matris nxn siempre tiene inversa siempre y cuando DetMatriz != 0
#ejemplo
det_B = np.linalg.det(B)
if det_B != 0:
    inv_B = np.linalg.inv(B)
    print("Inversa de B:\n", inv_B)
else:
    print("B no es invertible")

Inversa de B:
 [[ 0.5   0.  ]
 [-0.25  0.5 ]]


In [14]:
#descomposicion de matrices
print(A)
Q,R= np.linalg.qr(A)
#matriz Ortogonal
print("Factor Q:\n", Q)
#Matriz Triangular Superior
print("Factor R:\n", R)

[[1 2]
 [3 4]]
Factor Q:
 [[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
Factor R:
 [[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]


In [16]:
Q@R

array([[1., 2.],
       [3., 4.]])