In [1]:
#concepto clave:
#Solo se puede realizar Broadcasting si todas las dimensiones de los arrays son iguales o una de lleas es 1.
#Reglas del Broadcasting
#Regla 1: Si los arrays no tienen el mismo numero de dimensiones, se añade una dimension de tamaño 1 al inicio del array con menos dimensiones.
#Regla 2: Se comparan las dimensiones de los arrays. Si las dimensiones son iguales o una de ellas es 1, se puede continuar. Si no, se produce un error.
#Regla 3: Los arrays con dimensiones de tamaño 1 se expanden para coincidir con las otras dimensiones

In [2]:
#ejemplo visual
import numpy as np
vector = np.array([1,2,3])


In [4]:
#aqui sumamos 5 a cada elemento del vector
#en este caso se broadcastea haciendo un vector [5,5,5]
vector+5

array([6, 7, 8])

In [12]:
#puede ser igual para la multiplicacion de matrices
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
B = np.array([[1],
              [2],
              [3]])
print("array type A: \n", A)
print("array type B: \n", B)
print("Multiplication: \n",A*B)

array type A: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array type B: 
 [[1]
 [2]
 [3]]
Multiplication: 
 [[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]
