In [1]:
import numpy as np

In [5]:
z = np.array([2,3,4])
x = z
print('x: ', x)
print('z: ', z)

x:  [2 3 4]
z:  [2 3 4]


In [6]:
#pero que pasa si cambio un elemento en z?
z[1] = 9
print('x: ', x)
print('z: ', z)

x:  [2 9 4]
z:  [2 9 4]


In [7]:
#ambos cambian, que lo que haga en x o z van a ser afectados por su paralelo
#para evitar esto ocupamos el metodo copy()
x = z.copy()

In [9]:
#demostracion del cambio
#pero esto consume mas memoria
z[1] = 3
print('x: ', x)
print('z: ', z)

x:  [2 9 4]
z:  [2 3 4]


In [10]:
#cambiar la forma de un arreglo 
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [14]:
#cambiar la forma a 3x3
b = a.reshape(3,3)
#no se puede cambiar la forma a una mayor, puesto que se necesita el espacio de los elementos que hay en la lista
#es decir, si tengo n elementos debo hacer un array que ixj=n elementos
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
#para aplanar el arreglo
c = b.flatten() #primer metodo, donde crea una copia del array
c = c.ravel() #segundo metodo, donde apunta a los elementos del array
print(c)

[1 2 3 4 5 6 7 8 9]


In [21]:
#sacar matriz transpuesta
print(b.transpose()) #primer metodo
print(c.T) #Segundo metodo

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[1 2 3 4 5 6 7 8 9]


In [22]:
#reduccion de arreglos
np.sum(b) #suma de todos los elementos
np.min(b) #valor mas pequenio de todos los elementos
np.max(b) #valor mas grande de todos los elementos
np.mean(b) #media de todos los elementos
np.std(b) #desviacion estandar de todos los elementos

np.float64(2.581988897471611)

In [26]:
#reduccion de arreglos por columnas o filas que decidamos
np.sum(b, axis = 0) #suma de los elementos por filas
np.min(b, axis = 0) #valor mas pequenio de los elementos por filas
np.max(b, axis = 0) #valor mas grande de los elementos por filas
np.mean(b, axis = 0) #media de los elementos por filas
np.std(b, axis = 0) #desviacion estandar de los elementos por filas
#es lo mismo para las columnas pero el eje es 1 en vez de 0

array([2.44948974, 2.44948974, 2.44948974])