In [1]:
import numpy as np

In [2]:
#Sistema de ecuaciones convencional donde 
#3x+y=9
#x+2y=8
#el sistema matricial esta conformado por (Ax=b)
#cullo caso seria A= [3 1] B= [9]
#                    [1 2]    [8]
#la solucion se aplica con np.linalg.solve

In [5]:
#paso 1, definir nuestras matrices
A = np.array([[3,1],[1,2]])
#se tiene que poner en fila para que lo interprete la funcion
#aunque la matriz este declarada en columna
b = np.array([9, 8])
print(A)
print(b)

[[3 1]
 [1 2]]
[9 8]


In [8]:
#paso 2, aplicar el metodo solve
#x es referencia a la matriz de resultados
x = np.linalg.solve(A,b)
print("Solucion del sistema (matriz resultante):\n", x)

Solucion del sistema (matriz resultante):
 [2. 3.]


In [25]:
#Sistema de ecuaciones resuelto por la pesudo inversa
#Sistema de ecuaciones convencional donde 
#x+2y=1
#3x+4y=2
#4x+6y=3
#el sistema matricial esta conformado por (Ax=b)
#cullo caso seria A= [1 2] B= [1]
#                    [3 4]    [2]
#                    [5 6]    [3]
#la solucion se aplica con np.linalg.pinv

In [26]:
#paso 1, definir nuestras matrices
A = np.array([[1,2],[3,4],[5,6]])
#se tiene que poner en fila para que lo interprete la funcion
#aunque la matriz este declarada en columna
b = np.array([1,2,3])
print(A)
print(b)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3]


In [27]:
#paso 2, aplicar el metodo pinv
pinv_A = np.linalg.pinv(A)
print(pinv_A)

[[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]


In [29]:
#paso 3, sacar la matriz resultante multiplicando pinv_A x b
#x es referencia a la matriz de resultados
x = np.dot(pinv_A, b)
print("Solucion del sistema (matriz resultante):\n", x)
#esto fue metodo de minimos cuadrados

Solucion del sistema (matriz resultante):
 [0.  0.5]
